server:
  port: 8106

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 1.94.55.43:8848
  application:
    name: ts-user-service
  datasource:
    url: jdbc:mysql://${USER_MYSQL_HOST:1.94.55.43}:${USER_MYSQL_PORT:31306}/${USER_MYSQL_DATABASE:ts_user_mysql}?useSSL=false
    username: ${USER_MYSQL_USER:root}
    password: ${USER_MYSQL_PASSWORD:mysql@12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


swagger:
  controllerPackage: user.controller
