# HTTP Server
server:
  port: 8098  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:1.94.55.43:8848}
  application:
    name: ts-order-service
  datasource:
    url: jdbc:mysql://${ORDER_MYSQL_HOST:1.94.55.43}:${ORDER_MYSQL_PORT:31306}/${ORDER_MYSQL_DATABASE:ts}?useSSL=false
    username: ${ORDER_MYSQL_USER:root}
    password: ${ORDER_MYSQL_PASSWORD:mysql@12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: order.controller