spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:1.94.55.43:8848}
  application:
    name: ts-config-service
  datasource:
    url: jdbc:mysql://${CONSIGN_MYSQL_HOST:1.94.55.43}:${CONSIGN_MYSQL_PORT:31306}/${CONSIGN_MYSQL_DATABASE:ts_config_mysql}?useSSL=false
    username: ${CONSIGN_MYSQL_USER:root}
    password: ${CONSIGN_MYSQL_PASSWORD:mysql@12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


# HTTP Server
server:
  port: 8092  # HTTP (Tomcat) port

swagger:
  controllerPackage: config.controller