server:
  port: 8107  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 1.94.55.43:8848
  application:
    name: ts-verification-code-service

swagger:
  controllerPackage: verifycode.controller