server:
  port: 8101

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:1.94.55.43:8848}
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller
